apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: micro-spot
spec:
  template:
    metadata:
      labels:
        karpenter-smoke-test: "true"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: micro-spot
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.small", "t3a.small"]
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
  limits:
    nodes: 1
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m